# Generated by Django 2.1.3 on 2019-10-21 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlist', '0002_auto_20191021_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='toihan',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 11, 16, 25, 865554)),
        ),
    ]
